import { cn } from "@/lib/utils";

// Stroke widths from the fingerprint research, in viewBox units: the 52 px
// mark is drawn at its natural size, so 0.95 units = 0.95 px; the 220 px hero
// uses 1.35.
const STROKE_WIDTH = { thumb: 0.95, hero: 1.35 };

// The Song Fingerprint: a whole-track identity mark, distinct from the Song
// DNA timeline (Fingerprint.jsx). The lines are generated by
// scripts/build_library.py from where the track spends its time in
// tonality x brightness space; this only draws them. Monochrome
// (currentColor), static and with no time axis - it is the same mark
// whether or not the track is selected.
//
// `fingerprint` is { status: "available", path, viewBox } or
// { status: "unavailable", reason } (see lib/songFingerprint.js).
function SongFingerprint({ fingerprint, variant = "thumb", className }) {
  if (fingerprint?.status !== "available") {
    return (
      <div
        className={cn("rounded-md border border-dashed border-border", className)}
        title="No song fingerprint for this track"
      >
        <span className="sr-only">No song fingerprint for this track</span>
      </div>
    );
  }

  return (
    <svg
      viewBox={fingerprint.viewBox}
      className={className}
      fill="none"
      stroke="currentColor"
      strokeWidth={STROKE_WIDTH[variant]}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d={fingerprint.path} />
    </svg>
  );
}

export default SongFingerprint;
