// Base URL of the FastAPI backend. Override with VITE_API_URL (e.g. in
// frontend/.env.local) when the backend isn't on the default local address.
export const API_BASE = import.meta.env.VITE_API_URL ?? "http://127.0.0.1:8000";

// Where the precomputed song library (manifest, audio, features) is served
// from - static files under public/library, generated by scripts/build_library.py.
export const LIBRARY_BASE = `${import.meta.env.BASE_URL}library/`;
