// Song Fingerprint: a whole-track identity mark (where the track spends its
// time in chroma-entropy x brightness space, drawn as B1 ridge lines). It is
// separate from the Song DNA timeline and never blocks the library: anything
// missing or unexpected just leaves that track without a fingerprint.
//
// library.json carries a small "song_fingerprint" summary and, per track, a
// "song_fingerprint" reference; thumbnail paths live in fingerprints/thumbs.json.
// All of it is generated by scripts/build_library.py.

// Only fingerprints drawn with this frozen rule set are shown; a different
// version could mean different axes, so it isn't guessed at.
export const SUPPORTED_FINGERPRINT_VERSION = "E1B1/1";

export const UNAVAILABLE = {
  missing: "missing",
  unsupportedVersion: "unsupported_version",
  malformed: "malformed",
};

// E1B1/1 thumbnails are traced on a fixed 52 x 52 view; anything else is not
// this fingerprint.
export const THUMB_VIEW_BOX = "0 0 52 52";

// Fields that identify which build drew a fingerprint. thumbs.json must carry
// the same values as the manifest, so thumbnails from an older or different
// build (another corpus, Dref, parameter set or librosa) are never mixed in.
const IDENTITY_FIELDS = ["version", "params_hash", "librosa_version", "dref", "corpus_id"];

const NUMBER = String.raw`-?\d+(?:\.\d+)?`;
const POINT = `${NUMBER} ${NUMBER}`;
// Exactly what the generator writes: "M x yL x y..." runs, nothing else.
const PATH_DATA = new RegExp(`^(?:M${POINT}(?:L${POINT})*)+$`);
const SHA256 = /^[0-9a-f]{64}$/;

export function isValidPathData(value) {
  return typeof value === "string" && PATH_DATA.test(value);
}

function isPlainObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

// Types only - nothing is coerced. dref is null when no track has a fingerprint.
function hasValidIdentity(summary) {
  return (
    typeof summary.params_hash === "string" &&
    SHA256.test(summary.params_hash) &&
    typeof summary.corpus_id === "string" &&
    SHA256.test(summary.corpus_id) &&
    typeof summary.librosa_version === "string" &&
    summary.librosa_version.length > 0 &&
    (summary.dref === null || (Number.isFinite(summary.dref) && summary.dref > 0))
  );
}

// The manifest's global summary, or an unavailable reason for every track.
// Never throws: bad fingerprint metadata only disables fingerprints.
export function parseFingerprintSummary(summary) {
  if (!isPlainObject(summary)) return { ok: false, reason: UNAVAILABLE.missing };
  if (summary.version !== SUPPORTED_FINGERPRINT_VERSION) {
    return { ok: false, reason: UNAVAILABLE.unsupportedVersion };
  }
  if (
    typeof summary.thumbs !== "string" ||
    !summary.thumbs ||
    summary.thumb_view_box !== THUMB_VIEW_BOX ||
    !hasValidIdentity(summary)
  ) {
    return { ok: false, reason: UNAVAILABLE.malformed };
  }

  const identity = Object.fromEntries(IDENTITY_FIELDS.map((field) => [field, summary[field]]));
  return { ok: true, thumbsPath: summary.thumbs, viewBox: THUMB_VIEW_BOX, identity };
}

// fingerprints/thumbs.json -> { trackId: pathData }, or null if it doesn't
// belong to this summary's build or isn't shaped as expected. Individual
// invalid paths are dropped rather than failing the whole file.
export function parseThumbs(payload, summary) {
  if (!isPlainObject(payload)) return null;
  if (payload.view_box !== THUMB_VIEW_BOX) return null;
  if (IDENTITY_FIELDS.some((field) => payload[field] !== summary.identity[field])) return null;
  if (!isPlainObject(payload.thumbs)) return null;

  const thumbs = {};
  for (const [id, path] of Object.entries(payload.thumbs)) {
    if (isValidPathData(path)) thumbs[id] = path;
  }
  return thumbs;
}

// Adds `fingerprint` to each track:
//   { status: "available", path, viewBox }  or  { status: "unavailable", reason }
// `summary` is parseFingerprintSummary's result; `thumbs` is parseThumbs's.
export function attachFingerprints(tracks, summary, thumbs) {
  return tracks.map((track) => ({ ...track, fingerprint: trackFingerprint(track, summary, thumbs) }));
}

function trackFingerprint(track, summary, thumbs) {
  if (!summary.ok) return { status: "unavailable", reason: summary.reason };

  const ref = track.song_fingerprint;
  if (!ref || typeof ref !== "object") return { status: "unavailable", reason: UNAVAILABLE.missing };
  // The build found nothing to draw (e.g. an all-silent track) and said why.
  if (ref.artifact === null) {
    return { status: "unavailable", reason: ref.unavailable_reason || UNAVAILABLE.missing };
  }
  if (!thumbs) return { status: "unavailable", reason: UNAVAILABLE.malformed };

  const path = thumbs[track.id];
  if (!path) return { status: "unavailable", reason: UNAVAILABLE.malformed };
  return { status: "available", path, viewBox: summary.viewBox };
}
